### ISSUE TITLE
file permissions on pricing.rb (640 -> 644)

### ISSUE THREAD

**Issue by dereklwood** [kigster/joyent-cloud-pricing#1]
version 1.0.8 of the gem installs files without read permissions for "other".  This is causing load problems on systems where the gem is installed as a different user (ie, root) than the running application:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require': cannot load such file -- pricing (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/knife-joyent-0.4.8/lib/chef/knife/joyent_base.rb:2:in `<top (required)>'
```

I'm not familiar with what the standard rubygem best-practice is, but it should probably be consistent with knife-joyent, which has 644 permissions.

**Comment by hjhart** [comment]
Looks like this can be closed @kigster.
